spring:
  servlet:
    multipart:
      max-file-size: 10MB
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=postcard_shop
    driverClassName: org.postgresql.Driver
    username: login
    password: "password"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: false

